[2025-05-09T11:24:00.515+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:24:00.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:24:00.527+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:24:00.526+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:24:03.267+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:24:03.254+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:24:03.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:24:03.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.838 seconds
[2025-05-09T11:24:33.525+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:24:33.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:24:33.536+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:24:33.535+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:24:36.600+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:24:36.575+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:24:36.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:24:36.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 3.142 seconds
[2025-05-09T11:25:07.476+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:25:07.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:25:07.501+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:25:07.500+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:25:10.143+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:25:10.107+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:25:10.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:25:10.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.757 seconds
[2025-05-09T11:25:40.757+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:25:40.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:25:40.819+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:25:40.805+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:25:45.475+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:25:45.397+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:25:45.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:25:45.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 4.960 seconds
[2025-05-09T11:26:17.149+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:26:17.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:26:17.182+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:26:17.180+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:26:23.346+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:26:23.240+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:26:23.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:26:23.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 6.468 seconds
[2025-05-09T11:26:55.123+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:26:55.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:26:55.198+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:26:55.196+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:27:07.893+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:27:07.657+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:27:07.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:27:08.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 13.377 seconds
[2025-05-09T11:27:41.804+0000] {processor.py:186} INFO - Started process (PID=462) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:27:41.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:27:41.866+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:27:41.855+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:27:52.545+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:27:52.441+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:27:52.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:27:53.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 11.290 seconds
[2025-05-09T11:28:25.416+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:28:25.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:28:25.465+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:28:25.464+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:28:32.404+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:28:32.342+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:28:32.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:28:32.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 7.264 seconds
[2025-05-09T11:29:03.556+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:29:03.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:29:03.592+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:29:03.591+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:29:08.547+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:29:08.483+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:29:08.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:29:08.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 5.186 seconds
[2025-05-09T11:29:38.970+0000] {processor.py:186} INFO - Started process (PID=652) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:29:38.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:29:38.989+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:29:38.988+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:29:44.195+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:29:44.176+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:29:44.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:29:44.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 5.358 seconds
[2025-05-09T11:30:14.944+0000] {processor.py:186} INFO - Started process (PID=719) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:30:14.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:30:14.963+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:30:14.962+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:30:17.871+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:30:17.851+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:30:17.887+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:30:17.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 3.037 seconds
[2025-05-09T11:30:48.657+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/job_post.py
[2025-05-09T11:30:48.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T11:30:48.703+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:30:48.701+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T11:30:51.789+0000] {logging_mixin.py:190} INFO - [2025-05-09T11:30:51.747+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T11:30:51.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T11:30:51.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 3.346 seconds
[2025-05-09T13:39:03.038+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:39:03.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:39:03.045+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:39:03.044+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:39:03.874+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:39:03.864+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:39:03.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:39:03.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.876 seconds
[2025-05-09T13:39:34.516+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:39:34.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:39:34.623+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:39:34.623+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:39:35.570+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:39:35.561+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:39:35.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:39:35.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.084 seconds
[2025-05-09T13:40:06.343+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:40:06.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:40:06.350+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:40:06.350+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:40:07.618+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:40:07.608+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:40:07.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:40:07.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.330 seconds
[2025-05-09T13:40:37.983+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:40:37.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:40:37.988+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:40:37.987+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:40:38.908+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:40:38.898+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:40:38.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:40:38.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.961 seconds
[2025-05-09T13:41:09.752+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:41:09.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:41:09.758+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:41:09.758+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:41:10.440+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:41:10.431+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:41:10.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:41:10.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.723 seconds
[2025-05-09T13:41:40.941+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:41:40.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:41:40.945+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:41:40.945+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:41:41.504+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:41:41.495+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:41:41.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:41:41.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.596 seconds
[2025-05-09T13:42:11.613+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:42:11.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:42:11.617+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:42:11.617+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:42:12.365+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:42:12.357+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:42:12.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:42:12.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.787 seconds
[2025-05-09T13:42:42.661+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:42:42.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:42:42.666+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:42:42.666+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:42:43.795+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:42:43.786+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:42:43.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:42:43.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.191 seconds
[2025-05-09T13:43:14.110+0000] {processor.py:186} INFO - Started process (PID=596) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:43:14.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:43:14.119+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:43:14.119+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:43:14.896+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:43:14.888+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:43:14.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:43:14.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.829 seconds
[2025-05-09T13:43:45.645+0000] {processor.py:186} INFO - Started process (PID=662) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:43:45.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:43:45.656+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:43:45.655+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:43:47.065+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:43:47.051+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:43:47.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:43:47.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.480 seconds
[2025-05-09T13:44:17.540+0000] {processor.py:186} INFO - Started process (PID=727) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:44:17.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:44:17.545+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:44:17.545+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:44:18.557+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:44:18.544+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:44:18.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:44:18.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.074 seconds
[2025-05-09T13:44:49.283+0000] {processor.py:186} INFO - Started process (PID=793) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:44:49.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:44:49.288+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:44:49.288+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:44:50.211+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:44:50.202+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:44:50.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:44:50.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.964 seconds
[2025-05-09T13:45:20.438+0000] {processor.py:186} INFO - Started process (PID=859) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:45:20.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:45:20.444+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:45:20.443+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:45:21.253+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:45:21.244+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:45:21.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:45:21.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.855 seconds
[2025-05-09T13:45:51.348+0000] {processor.py:186} INFO - Started process (PID=926) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:45:51.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:45:51.352+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:45:51.352+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:45:52.064+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:45:52.057+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:45:52.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:45:52.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.746 seconds
[2025-05-09T13:46:22.425+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:46:22.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:46:22.432+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:46:22.432+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:46:23.678+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:46:23.665+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:46:23.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:46:23.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.318 seconds
[2025-05-09T13:46:54.646+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:46:54.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:46:54.659+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:46:54.658+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:46:56.843+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:46:56.827+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:46:56.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:46:56.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.272 seconds
[2025-05-09T13:47:30.058+0000] {processor.py:186} INFO - Started process (PID=1126) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:47:30.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:47:30.078+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:47:30.076+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:47:32.969+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:47:32.943+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:47:32.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:47:33.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 3.019 seconds
[2025-05-09T13:48:03.839+0000] {processor.py:186} INFO - Started process (PID=1193) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:48:03.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:48:03.860+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:48:03.859+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:48:05.950+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:48:05.932+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:48:05.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:48:06.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.197 seconds
[2025-05-09T13:48:36.243+0000] {processor.py:186} INFO - Started process (PID=1260) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:48:36.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:48:36.251+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:48:36.250+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:48:37.619+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:48:37.605+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:48:37.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:48:37.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.433 seconds
[2025-05-09T13:49:08.176+0000] {processor.py:186} INFO - Started process (PID=1323) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:49:08.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:49:08.186+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:49:08.185+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:49:09.700+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:49:09.682+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:49:09.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:49:09.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.605 seconds
[2025-05-09T13:49:40.274+0000] {processor.py:186} INFO - Started process (PID=1389) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:49:40.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:49:40.283+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:49:40.282+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:49:42.366+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:49:42.348+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:49:42.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:49:42.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.167 seconds
[2025-05-09T13:50:12.817+0000] {processor.py:186} INFO - Started process (PID=1456) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:50:12.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:50:12.828+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:50:12.828+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:50:13.854+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:50:13.793+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:50:13.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:50:13.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.074 seconds
[2025-05-09T13:50:44.366+0000] {processor.py:186} INFO - Started process (PID=1520) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:50:44.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:50:44.370+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:50:44.369+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:50:45.170+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:50:45.151+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:50:45.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:50:45.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.844 seconds
[2025-05-09T13:51:16.011+0000] {processor.py:186} INFO - Started process (PID=1586) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:51:16.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:51:16.020+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:51:16.019+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:51:17.474+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:51:17.463+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:51:17.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:51:17.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.512 seconds
[2025-05-09T13:51:48.323+0000] {processor.py:186} INFO - Started process (PID=1651) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:51:48.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:51:48.332+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:51:48.331+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:51:50.511+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:51:50.487+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:51:50.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:51:50.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.267 seconds
[2025-05-09T13:52:20.792+0000] {processor.py:186} INFO - Started process (PID=1717) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:52:20.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:52:20.810+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:52:20.809+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:52:23.830+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:52:23.781+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:52:23.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:52:23.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 3.184 seconds
[2025-05-09T13:52:54.867+0000] {processor.py:186} INFO - Started process (PID=1784) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:52:54.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:52:54.875+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:52:54.874+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:52:56.130+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:52:56.117+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:52:56.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:52:56.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.346 seconds
[2025-05-09T13:53:26.869+0000] {processor.py:186} INFO - Started process (PID=1854) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:53:26.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:53:26.876+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:53:26.876+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:53:27.876+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:53:27.866+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:53:27.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:53:27.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.047 seconds
[2025-05-09T13:53:58.184+0000] {processor.py:186} INFO - Started process (PID=1918) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:53:58.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:53:58.190+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:53:58.189+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:53:59.212+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:53:59.199+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:53:59.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:53:59.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.079 seconds
[2025-05-09T13:54:29.991+0000] {processor.py:186} INFO - Started process (PID=1982) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:54:29.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:54:29.995+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:54:29.994+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:54:30.611+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:54:30.604+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:54:30.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:54:30.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.645 seconds
[2025-05-09T13:55:01.261+0000] {processor.py:186} INFO - Started process (PID=2045) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:55:01.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:55:01.276+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:55:01.275+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:55:03.405+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:55:03.386+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:55:03.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:55:03.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.249 seconds
[2025-05-09T13:55:34.364+0000] {processor.py:186} INFO - Started process (PID=2108) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:55:34.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:55:34.372+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:55:34.372+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:55:35.693+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:55:35.681+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:55:35.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:55:35.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.383 seconds
[2025-05-09T13:56:05.897+0000] {processor.py:186} INFO - Started process (PID=2173) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:56:05.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:56:05.903+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:56:05.902+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:56:06.927+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:56:06.918+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:56:06.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:56:06.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.068 seconds
[2025-05-09T13:56:37.306+0000] {processor.py:186} INFO - Started process (PID=2236) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:56:37.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:56:37.315+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:56:37.315+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:56:38.998+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:56:38.960+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:56:39.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:56:39.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.758 seconds
[2025-05-09T13:57:09.553+0000] {processor.py:186} INFO - Started process (PID=2299) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:57:09.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:57:09.562+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:57:09.561+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:57:10.919+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:57:10.907+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:57:10.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:57:10.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.415 seconds
[2025-05-09T13:57:41.146+0000] {processor.py:186} INFO - Started process (PID=2362) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:57:41.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:57:41.154+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:57:41.153+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:57:43.158+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:57:43.134+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:57:43.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:57:43.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 2.116 seconds
[2025-05-09T13:58:13.386+0000] {processor.py:186} INFO - Started process (PID=2427) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:58:13.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:58:13.390+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:58:13.390+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:58:14.325+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:58:14.313+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:58:14.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:58:14.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.985 seconds
[2025-05-09T13:58:45.223+0000] {processor.py:186} INFO - Started process (PID=2493) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:58:45.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:58:45.229+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:58:45.228+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:58:46.079+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:58:46.070+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:58:46.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:58:46.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.895 seconds
[2025-05-09T13:59:16.231+0000] {processor.py:186} INFO - Started process (PID=2559) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:59:16.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:59:16.235+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:59:16.235+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:59:17.160+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:59:17.151+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:59:17.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:59:17.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.966 seconds
[2025-05-09T13:59:47.276+0000] {processor.py:186} INFO - Started process (PID=2626) to work on /opt/airflow/dags/job_post.py
[2025-05-09T13:59:47.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T13:59:47.281+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:59:47.280+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T13:59:48.250+0000] {logging_mixin.py:190} INFO - [2025-05-09T13:59:48.242+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T13:59:48.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T13:59:48.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.012 seconds
[2025-05-09T14:00:18.690+0000] {processor.py:186} INFO - Started process (PID=2692) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:00:18.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:00:18.697+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:00:18.696+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:00:19.930+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:00:19.915+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:00:19.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:00:19.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.306 seconds
[2025-05-09T14:00:51.094+0000] {processor.py:186} INFO - Started process (PID=2755) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:00:51.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:00:51.108+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:00:51.107+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:00:52.937+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:00:52.920+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:00:52.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:00:53.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.930 seconds
[2025-05-09T14:01:23.190+0000] {processor.py:186} INFO - Started process (PID=2821) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:01:23.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:01:23.196+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:01:23.195+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:01:23.966+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:01:23.952+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:01:23.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:01:24.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.827 seconds
[2025-05-09T14:01:54.396+0000] {processor.py:186} INFO - Started process (PID=2884) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:01:54.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:01:54.399+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:01:54.399+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:01:54.965+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:01:54.956+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:01:54.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:01:54.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.593 seconds
[2025-05-09T14:02:25.838+0000] {processor.py:186} INFO - Started process (PID=2949) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:02:25.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:02:25.842+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:02:25.841+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:02:26.460+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:02:26.450+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:02:26.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:02:26.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.647 seconds
[2025-05-09T14:02:57.105+0000] {processor.py:186} INFO - Started process (PID=3018) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:02:57.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:02:57.117+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:02:57.116+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:02:58.333+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:02:58.321+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:02:58.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:02:58.376+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.280 seconds
[2025-05-09T14:03:28.602+0000] {processor.py:186} INFO - Started process (PID=3082) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:03:28.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:03:28.609+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:03:28.608+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:03:29.691+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:03:29.613+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:03:29.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:03:29.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.154 seconds
[2025-05-09T14:03:59.861+0000] {processor.py:186} INFO - Started process (PID=3148) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:03:59.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:03:59.873+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:03:59.872+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:04:01.431+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:04:01.414+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:04:01.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:04:01.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.640 seconds
[2025-05-09T14:04:31.608+0000] {processor.py:186} INFO - Started process (PID=3213) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:04:31.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:04:31.614+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:04:31.613+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:04:32.421+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:04:32.410+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:04:32.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:04:32.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.850 seconds
[2025-05-09T14:05:02.845+0000] {processor.py:186} INFO - Started process (PID=3278) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:05:02.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:05:02.850+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:05:02.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:05:03.446+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:05:03.439+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:05:03.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:05:03.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 0.625 seconds
[2025-05-09T14:05:33.707+0000] {processor.py:186} INFO - Started process (PID=3341) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:05:33.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:05:33.714+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:05:33.713+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:05:34.676+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:05:34.669+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:05:34.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:05:34.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.029 seconds
[2025-05-09T14:06:05.209+0000] {processor.py:186} INFO - Started process (PID=3405) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:06:05.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:06:05.216+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:06:05.215+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:06:06.493+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:06:06.479+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:06:06.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:06:06.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.336 seconds
[2025-05-09T14:06:36.761+0000] {processor.py:186} INFO - Started process (PID=3469) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:06:36.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:06:36.770+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:06:36.768+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:06:38.176+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:06:38.160+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:06:38.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:06:38.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.494 seconds
[2025-05-09T14:07:08.490+0000] {processor.py:186} INFO - Started process (PID=3533) to work on /opt/airflow/dags/job_post.py
[2025-05-09T14:07:08.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/job_post.py for tasks to queue
[2025-05-09T14:07:08.495+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:07:08.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/job_post.py
[2025-05-09T14:07:09.455+0000] {logging_mixin.py:190} INFO - [2025-05-09T14:07:09.372+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/job_post.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/job_post.py", line 16, in <module>
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-05-09T14:07:09.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/job_post.py
[2025-05-09T14:07:09.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/job_post.py took 1.022 seconds
